export const indianStates = [
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chhattisgarh',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal',
  ];

  export const citiesByState =
    {
      "Andaman and Nicobar Islands": [
        "Port Blair"
      ],
      "Haryana": [
        "Faridabad",
        "Gurgaon",
        "Hisar",
        "Rohtak",
        "Panipat",
        "Karnal",
        "Sonipat",
        "Yamunanagar",
        "Panchkula",
        "Bhiwani",
        "Bahadurgarh",
        "Jind",
        "Sirsa",
        "Thanesar",
        "Kaithal",
        "Palwal",
        "Rewari",
        "Hansi",
        "Narnaul",
        "Fatehabad",
        "Gohana",
        "Tohana",
        "Narwana",
        "Mandi Dabwali",
        "Charkhi Dadri",
        "Shahbad",
        "Pehowa",
        "Samalkha",
        "Pinjore",
        "Ladwa",
        "Sohna",
        "Safidon",
        "Taraori",
        "Mahendragarh",
        "Ratia",
        "Rania",
        "Sarsod"
      ],
      "Tamil Nadu": [
        "Chennai",
        "Coimbatore",
        "Madurai",
        "Tiruchirappalli",
        "Salem",
        "Tirunelveli",
        "Tiruppur",
        "Ranipet",
        "Nagercoil",
        "Thanjavur",
        "Vellore",
        "Kancheepuram",
        "Erode",
        "Tiruvannamalai",
        "Pollachi",
        "Rajapalayam",
        "Sivakasi",
        "Pudukkottai",
        "Neyveli (TS)",
        "Nagapattinam",
        "Viluppuram",
        "Tiruchengode",
        "Vaniyambadi",
        "Theni Allinagaram",
        "Udhagamandalam",
        "Aruppukkottai",
        "Paramakudi",
        "Arakkonam",
        "Virudhachalam",
        "Srivilliputhur",
        "Tindivanam",
        "Virudhunagar",
        "Karur",
        "Valparai",
        "Sankarankovil",
        "Tenkasi",
        "Palani",
        "Pattukkottai",
        "Tirupathur",
        "Ramanathapuram",
        "Udumalaipettai",
        "Gobichettipalayam",
        "Thiruvarur",
        "Thiruvallur",
        "Panruti",
        "Namakkal",
        "Thirumangalam",
        "Vikramasingapuram",
        "Nellikuppam",
        "Rasipuram",
        "Tiruttani",
        "Nandivaram-Guduvancheri",
        "Periyakulam",
        "Pernampattu",
        "Vellakoil",
        "Sivaganga",
        "Vadalur",
        "Rameshwaram",
        "Tiruvethipuram",
        "Perambalur",
        "Usilampatti",
        "Vedaranyam",
        "Sathyamangalam",
        "Puliyankudi",
        "Nanjikottai",
        "Thuraiyur",
        "Sirkali",
        "Tiruchendur",
        "Periyasemur",
        "Sattur",
        "Vandavasi",
        "Tharamangalam",
        "Tirukkoyilur",
        "Oddanchatram",
        "Palladam",
        "Vadakkuvalliyur",
        "Tirukalukundram",
        "Uthamapalayam",
        "Surandai",
        "Sankari",
        "Shenkottai",
        "Vadipatti",
        "Sholingur",
        "Tirupathur",
        "Manachanallur",
        "Viswanatham",
        "Polur",
        "Panagudi",
        "Uthiramerur",
        "Thiruthuraipoondi",
        "Pallapatti",
        "Ponneri",
        "Lalgudi",
        "Natham",
        "Unnamalaikadai",
        "P.N.Patti",
        "Tharangambadi",
        "Tittakudi",
        "Pacode",
        "O' Valley",
        "Suriyampalayam",
        "Sholavandan",
        "Thammampatti",
        "Namagiripettai",
        "Peravurani",
        "Parangipettai",
        "Pudupattinam",
        "Pallikonda",
        "Sivagiri",
        "Punjaipugalur",
        "Padmanabhapuram",
        "Thirupuvanam"
      ],
      "Madhya Pradesh": [
        "Indore",
        "Bhopal",
        "Jabalpur",
        "Gwalior",
        "Ujjain",
        "Sagar",
        "Ratlam",
        "Satna",
        "Murwara (Katni)",
        "Morena",
        "Singrauli",
        "Rewa",
        "Vidisha",
        "Ganjbasoda",
        "Shivpuri",
        "Mandsaur",
        "Neemuch",
        "Nagda",
        "Itarsi",
        "Sarni",
        "Sehore",
        "Mhow Cantonment",
        "Seoni",
        "Balaghat",
        "Ashok Nagar",
        "Tikamgarh",
        "Shahdol",
        "Pithampur",
        "Alirajpur",
        "Mandla",
        "Sheopur",
        "Shajapur",
        "Panna",
        "Raghogarh-Vijaypur",
        "Sendhwa",
        "Sidhi",
        "Pipariya",
        "Shujalpur",
        "Sironj",
        "Pandhurna",
        "Nowgong",
        "Mandideep",
        "Sihora",
        "Raisen",
        "Lahar",
        "Maihar",
        "Sanawad",
        "Sabalgarh",
        "Umaria",
        "Porsa",
        "Narsinghgarh",
        "Malaj Khand",
        "Sarangpur",
        "Mundi",
        "Nepanagar",
        "Pasan",
        "Mahidpur",
        "Seoni-Malwa",
        "Rehli",
        "Manawar",
        "Rahatgarh",
        "Panagar",
        "Wara Seoni",
        "Tarana",
        "Sausar",
        "Rajgarh",
        "Niwari",
        "Mauganj",
        "Manasa",
        "Nainpur",
        "Prithvipur",
        "Sohagpur",
        "Nowrozabad (Khodargama)",
        "Shamgarh",
        "Maharajpur",
        "Multai",
        "Pali",
        "Pachore",
        "Rau",
        "Mhowgaon",
        "Vijaypur",
        "Narsinghgarh"
      ],
      "Jharkhand": [
        "Dhanbad",
        "Ranchi",
        "Jamshedpur",
        "Bokaro Steel City",
        "Deoghar",
        "Phusro",
        "Adityapur",
        "Hazaribag",
        "Giridih",
        "Ramgarh",
        "Jhumri Tilaiya",
        "Saunda",
        "Sahibganj",
        "Medininagar (Daltonganj)",
        "Chaibasa",
        "Chatra",
        "Gumia",
        "Dumka",
        "Madhupur",
        "Chirkunda",
        "Pakaur",
        "Simdega",
        "Musabani",
        "Mihijam",
        "Patratu",
        "Lohardaga",
        "Tenu dam-cum-Kathhara"
      ],
      "Mizoram": [
        "Aizawl",
        "Lunglei",
        "Saiha"
      ],
      "Nagaland": [
        "Dimapur",
        "Kohima",
        "Zunheboto",
        "Tuensang",
        "Wokha",
        "Mokokchung"
      ],
      "Himachal Pradesh": [
        "Shimla",
        "Mandi",
        "Solan",
        "Nahan",
        "Sundarnagar",
        "Palampur",
        "Kullu"
      ],
      "Tripura": [
        "Agartala",
        "Udaipur",
        "Dharmanagar",
        "Pratapgarh",
        "Kailasahar",
        "Belonia",
        "Khowai"
      ],
      "Andhra Pradesh": [
        "Visakhapatnam",
        "Vijayawada",
        "Guntur",
        "Nellore",
        "Kurnool",
        "Rajahmundry",
        "Kakinada",
        "Tirupati",
        "Anantapur",
        "Kadapa",
        "Vizianagaram",
        "Eluru",
        "Ongole",
        "Nandyal",
        "Machilipatnam",
        "Adoni",
        "Tenali",
        "Chittoor",
        "Hindupur",
        "Proddatur",
        "Bhimavaram",
        "Madanapalle",
        "Guntakal",
        "Dharmavaram",
        "Gudivada",
        "Srikakulam",
        "Narasaraopet",
        "Rajampet",
        "Tadpatri",
        "Tadepalligudem",
        "Chilakaluripet",
        "Yemmiganur",
        "Kadiri",
        "Chirala",
        "Anakapalle",
        "Kavali",
        "Palacole",
        "Sullurpeta",
        "Tanuku",
        "Rayachoti",
        "Srikalahasti",
        "Bapatla",
        "Naidupet",
        "Nagari",
        "Gudur",
        "Vinukonda",
        "Narasapuram",
        "Nuzvid",
        "Markapur",
        "Ponnur",
        "Kandukur",
        "Bobbili",
        "Rayadurg",
        "Samalkot",
        "Jaggaiahpet",
        "Tuni",
        "Amalapuram",
        "Bheemunipatnam",
        "Venkatagiri",
        "Sattenapalle",
        "Pithapuram",
        "Palasa Kasibugga",
        "Parvathipuram",
        "Macherla",
        "Gooty",
        "Salur",
        "Mandapeta",
        "Jammalamadugu",
        "Peddapuram",
        "Punganur",
        "Nidadavole",
        "Repalle",
        "Ramachandrapuram",
        "Kovvur",
        "Tiruvuru",
        "Uravakonda",
        "Narsipatnam",
        "Yerraguntla",
        "Pedana",
        "Puttur",
        "Renigunta",
        "Rajam",
        "Srisailam Project (Right Flank Colony) Township"
      ],
      "Punjab": [
        "Ludhiana",
        "Patiala",
        "Amritsar",
        "Jalandhar",
        "Bathinda",
        "Pathankot",
        "Hoshiarpur",
        "Batala",
        "Moga",
        "Malerkotla",
        "Khanna",
        "Mohali",
        "Barnala",
        "Firozpur",
        "Phagwara",
        "Kapurthala",
        "Zirakpur",
        "Kot Kapura",
        "Faridkot",
        "Muktsar",
        "Rajpura",
        "Sangrur",
        "Fazilka",
        "Gurdaspur",
        "Kharar",
        "Gobindgarh",
        "Mansa",
        "Malout",
        "Nabha",
        "Tarn Taran",
        "Jagraon",
        "Sunam",
        "Dhuri",
        "Firozpur Cantt.",
        "Sirhind Fatehgarh Sahib",
        "Rupnagar",
        "Jalandhar Cantt.",
        "Samana",
        "Nawanshahr",
        "Rampura Phul",
        "Nangal",
        "Nakodar",
        "Zira",
        "Patti",
        "Raikot",
        "Longowal",
        "Urmar Tanda",
        "Morinda, India",
        "Phillaur",
        "Pattran",
        "Qadian",
        "Sujanpur",
        "Mukerian",
        "Talwara"
      ],
      "Chandigarh": [
        "Chandigarh"
      ],
      "Rajasthan": [
        "Jaipur",
        "Jodhpur",
        "Bikaner",
        "Udaipur",
        "Ajmer",
        "Bhilwara",
        "Alwar",
        "Bharatpur",
        "Pali",
        "Barmer",
        "Sikar",
        "Tonk",
        "Sadulpur",
        "Sawai Madhopur",
        "Nagaur",
        "Makrana",
        "Sujangarh",
        "Sardarshahar",
        "Ladnu",
        "Ratangarh",
        "Nokha",
        "Nimbahera",
        "Suratgarh",
        "Rajsamand",
        "Lachhmangarh",
        "Rajgarh (Churu)",
        "Nasirabad",
        "Nohar",
        "Phalodi",
        "Nathdwara",
        "Pilani",
        "Merta City",
        "Sojat",
        "Neem-Ka-Thana",
        "Sirohi",
        "Pratapgarh",
        "Rawatbhata",
        "Sangaria",
        "Lalsot",
        "Pilibanga",
        "Pipar City",
        "Taranagar",
        "Vijainagar, Ajmer",
        "Sumerpur",
        "Sagwara",
        "Ramganj Mandi",
        "Lakheri",
        "Udaipurwati",
        "Losal",
        "Sri Madhopur",
        "Ramngarh",
        "Rawatsar",
        "Rajakhera",
        "Shahpura",
        "Shahpura",
        "Raisinghnagar",
        "Malpura",
        "Nadbai",
        "Sanchore",
        "Nagar",
        "Rajgarh (Alwar)",
        "Sheoganj",
        "Sadri",
        "Todaraisingh",
        "Todabhim",
        "Reengus",
        "Rajaldesar",
        "Sadulshahar",
        "Sambhar",
        "Prantij",
        "Mount Abu",
        "Mangrol",
        "Phulera",
        "Mandawa",
        "Pindwara",
        "Mandalgarh",
        "Takhatgarh"
      ],
      "Assam": [
        "Guwahati",
        "Silchar",
        "Dibrugarh",
        "Nagaon",
        "Tinsukia",
        "Jorhat",
        "Bongaigaon City",
        "Dhubri",
        "Diphu",
        "North Lakhimpur",
        "Tezpur",
        "Karimganj",
        "Sibsagar",
        "Goalpara",
        "Barpeta",
        "Lanka",
        "Lumding",
        "Mankachar",
        "Nalbari",
        "Rangia",
        "Margherita",
        "Mangaldoi",
        "Silapathar",
        "Mariani",
        "Marigaon"
      ],
      "Odisha": [
        "Bhubaneswar",
        "Cuttack",
        "Raurkela",
        "Brahmapur",
        "Sambalpur",
        "Puri",
        "Baleshwar Town",
        "Baripada Town",
        "Bhadrak",
        "Balangir",
        "Jharsuguda",
        "Bargarh",
        "Paradip",
        "Bhawanipatna",
        "Dhenkanal",
        "Barbil",
        "Kendujhar",
        "Sunabeda",
        "Rayagada",
        "Jatani",
        "Byasanagar",
        "Kendrapara",
        "Rajagangapur",
        "Parlakhemundi",
        "Talcher",
        "Sundargarh",
        "Phulabani",
        "Pattamundai",
        "Titlagarh",
        "Nabarangapur",
        "Soro",
        "Malkangiri",
        "Rairangpur",
        "Tarbha"
      ],
      "Chhattisgarh": [
        "Raipur",
        "Bhilai Nagar",
        "Korba",
        "Bilaspur",
        "Durg",
        "Rajnandgaon",
        "Jagdalpur",
        "Raigarh",
        "Ambikapur",
        "Mahasamund",
        "Dhamtari",
        "Chirmiri",
        "Bhatapara",
        "Dalli-Rajhara",
        "Naila Janjgir",
        "Tilda Newra",
        "Mungeli",
        "Manendragarh",
        "Sakti"
      ],
      "Jammu and Kashmir": [
        "Srinagar",
        "Jammu",
        "Baramula",
        "Anantnag",
        "Sopore",
        "KathUrban Agglomeration",
        "Rajauri",
        "Punch",
        "Udhampur"
      ],
      "Karnataka": [
        "Bengaluru",
        "Hubli-Dharwad",
        "Belagavi",
        "Mangaluru",
        "Davanagere",
        "Ballari",
        "Mysore",
        "Tumkur",
        "Shivamogga",
        "Raayachuru",
        "Robertson Pet",
        "Kolar",
        "Mandya",
        "Udupi",
        "Chikkamagaluru",
        "Karwar",
        "Ranebennuru",
        "Ranibennur",
        "Ramanagaram",
        "Gokak",
        "Yadgir",
        "Rabkavi Banhatti",
        "Shahabad",
        "Sirsi",
        "Sindhnur",
        "Tiptur",
        "Arsikere",
        "Nanjangud",
        "Sagara",
        "Sira",
        "Puttur",
        "Athni",
        "Mulbagal",
        "Surapura",
        "Siruguppa",
        "Mudhol",
        "Sidlaghatta",
        "Shahpur",
        "Saundatti-Yellamma",
        "Wadi",
        "Manvi",
        "Nelamangala",
        "Lakshmeshwar",
        "Ramdurg",
        "Nargund",
        "Tarikere",
        "Malavalli",
        "Savanur",
        "Lingsugur",
        "Vijayapura",
        "Sankeshwara",
        "Madikeri",
        "Talikota",
        "Sedam",
        "Shikaripur",
        "Mahalingapura",
        "Mudalagi",
        "Muddebihal",
        "Pavagada",
        "Malur",
        "Sindhagi",
        "Sanduru",
        "Afzalpur",
        "Maddur",
        "Madhugiri",
        "Tekkalakote",
        "Terdal",
        "Mudabidri",
        "Magadi",
        "Navalgund",
        "Shiggaon",
        "Shrirangapattana",
        "Sindagi",
        "Sakaleshapura",
        "Srinivaspur",
        "Ron",
        "Mundargi",
        "Sadalagi",
        "Piriyapatna",
        "Adyar"
      ],
      "Manipur": [
        "Imphal",
        "Thoubal",
        "Lilong",
        "Mayang Imphal"
      ],
      "Kerala": [
        "Thiruvananthapuram",
        "Kochi",
        "Kozhikode",
        "Kollam",
        "Thrissur",
        "Palakkad",
        "Alappuzha",
        "Malappuram",
        "Ponnani",
        "Vatakara",
        "Kanhangad",
        "Taliparamba",
        "Koyilandy",
        "Neyyattinkara",
        "Kayamkulam",
        "Nedumangad",
        "Kannur",
        "Tirur",
        "Kottayam",
        "Kasaragod",
        "Kunnamkulam",
        "Ottappalam",
        "Thiruvalla",
        "Thodupuzha",
        "Chalakudy",
        "Changanassery",
        "Punalur",
        "Nilambur",
        "Cherthala",
        "Perinthalmanna",
        "Mattannur",
        "Shoranur",
        "Varkala",
        "Paravoor",
        "Pathanamthitta",
        "Peringathur",
        "Attingal",
        "Kodungallur",
        "Pappinisseri",
        "Chittur-Thathamangalam",
        "Muvattupuzha",
        "Adoor",
        "Mavelikkara",
        "Mavoor",
        "Perumbavoor",
        "Vaikom",
        "Palai",
        "Panniyannur",
        "Guruvayoor",
        "Puthuppally",
        "Panamattom"
      ],
      "Delhi": [
        "Delhi",
        "New Delhi"
      ],
      "Dadra and Nagar Haveli": [
        "Silvassa"
      ],
      "Puducherry": [
        "Pondicherry",
        "Karaikal",
        "Yanam",
        "Mahe"
      ],
      "Uttarakhand": [
        "Dehradun",
        "Hardwar",
        "Haldwani-cum-Kathgodam",
        "Srinagar",
        "Kashipur",
        "Roorkee",
        "Rudrapur",
        "Rishikesh",
        "Ramnagar",
        "Pithoragarh",
        "Manglaur",
        "Nainital",
        "Mussoorie",
        "Tehri",
        "Pauri",
        "Nagla",
        "Sitarganj",
        "Bageshwar"
      ],
      "Uttar Pradesh": [
        "Lucknow",
        "Kanpur",
        "Firozabad",
        "Agra",
        "Meerut",
        "Varanasi",
        "Allahabad",
        "Amroha",
        "Moradabad",
        "Aligarh",
        "Saharanpur",
        "Noida",
        "Loni",
        "Jhansi",
        "Shahjahanpur",
        "Rampur",
        "Modinagar",
        "Hapur",
        "Etawah",
        "Sambhal",
        "Orai",
        "Bahraich",
        "Unnao",
        "Rae Bareli",
        "Lakhimpur",
        "Sitapur",
        "Lalitpur",
        "Pilibhit",
        "Chandausi",
        "Hardoi ",
        "Azamgarh",
        "Khair",
        "Sultanpur",
        "Tanda",
        "Nagina",
        "Shamli",
        "Najibabad",
        "Shikohabad",
        "Sikandrabad",
        "Shahabad, Hardoi",
        "Pilkhuwa",
        "Renukoot",
        "Vrindavan",
        "Ujhani",
        "Laharpur",
        "Tilhar",
        "Sahaswan",
        "Rath",
        "Sherkot",
        "Kalpi",
        "Tundla",
        "Sandila",
        "Nanpara",
        "Sardhana",
        "Nehtaur",
        "Seohara",
        "Padrauna",
        "Mathura",
        "Thakurdwara",
        "Nawabganj",
        "Siana",
        "Noorpur",
        "Sikandra Rao",
        "Puranpur",
        "Rudauli",
        "Thana Bhawan",
        "Palia Kalan",
        "Zaidpur",
        "Nautanwa",
        "Zamania",
        "Shikarpur, Bulandshahr",
        "Naugawan Sadat",
        "Fatehpur Sikri",
        "Shahabad, Rampur",
        "Robertsganj",
        "Utraula",
        "Sadabad",
        "Rasra",
        "Lar",
        "Lal Gopalganj Nindaura",
        "Sirsaganj",
        "Pihani",
        "Shamsabad, Agra",
        "Rudrapur",
        "Soron",
        "SUrban Agglomerationr",
        "Samdhan",
        "Sahjanwa",
        "Rampur Maniharan",
        "Sumerpur",
        "Shahganj",
        "Tulsipur",
        "Tirwaganj",
        "PurqUrban Agglomerationzi",
        "Shamsabad, Farrukhabad",
        "Warhapur",
        "Powayan",
        "Sandi",
        "Achhnera",
        "Naraura",
        "Nakur",
        "Sahaspur",
        "Safipur",
        "Reoti",
        "Sikanderpur",
        "Saidpur",
        "Sirsi",
        "Purwa",
        "Parasi",
        "Lalganj",
        "Phulpur",
        "Shishgarh",
        "Sahawar",
        "Samthar",
        "Pukhrayan",
        "Obra",
        "Niwai",
        "Mirzapur"
      ],
      "Bihar": [
        "Patna",
        "Gaya",
        "Bhagalpur",
        "Muzaffarpur",
        "Darbhanga",
        "Arrah",
        "Begusarai",
        "Chhapra",
        "Katihar",
        "Munger",
        "Purnia",
        "Saharsa",
        "Sasaram",
        "Hajipur",
        "Dehri-on-Sone",
        "Bettiah",
        "Motihari",
        "Bagaha",
        "Siwan",
        "Kishanganj",
        "Jamalpur",
        "Buxar",
        "Jehanabad",
        "Aurangabad",
        "Lakhisarai",
        "Nawada",
        "Jamui",
        "Sitamarhi",
        "Araria",
        "Gopalganj",
        "Madhubani",
        "Masaurhi",
        "Samastipur",
        "Mokameh",
        "Supaul",
        "Dumraon",
        "Arwal",
        "Forbesganj",
        "BhabUrban Agglomeration",
        "Narkatiaganj",
        "Naugachhia",
        "Madhepura",
        "Sheikhpura",
        "Sultanganj",
        "Raxaul Bazar",
        "Ramnagar",
        "Mahnar Bazar",
        "Warisaliganj",
        "Revelganj",
        "Rajgir",
        "Sonepur",
        "Sherghati",
        "Sugauli",
        "Makhdumpur",
        "Maner",
        "Rosera",
        "Nokha",
        "Piro",
        "Rafiganj",
        "Marhaura",
        "Mirganj",
        "Lalganj",
        "Murliganj",
        "Motipur",
        "Manihari",
        "Sheohar",
        "Maharajganj",
        "Silao",
        "Barh",
        "Asarganj"
      ],
      "Gujarat": [
        "Ahmedabad",
        "Surat",
        "Vadodara",
        "Rajkot",
        "Bhavnagar",
        "Jamnagar",
        "Nadiad",
        "Porbandar",
        "Anand",
        "Morvi",
        "Mahesana",
        "Bharuch",
        "Vapi",
        "Navsari",
        "Veraval",
        "Bhuj",
        "Godhra",
        "Palanpur",
        "Valsad",
        "Patan",
        "Deesa",
        "Amreli",
        "Anjar",
        "Dhoraji",
        "Khambhat",
        "Mahuva",
        "Keshod",
        "Wadhwan",
        "Ankleshwar",
        "Savarkundla",
        "Kadi",
        "Visnagar",
        "Upleta",
        "Una",
        "Sidhpur",
        "Unjha",
        "Mangrol",
        "Viramgam",
        "Modasa",
        "Palitana",
        "Petlad",
        "Kapadvanj",
        "Sihor",
        "Wankaner",
        "Limbdi",
        "Mandvi",
        "Thangadh",
        "Vyara",
        "Padra",
        "Lunawada",
        "Rajpipla",
        "Vapi",
        "Umreth",
        "Sanand",
        "Rajula",
        "Radhanpur",
        "Mahemdabad",
        "Ranavav",
        "Tharad",
        "Mansa",
        "Umbergaon",
        "Talaja",
        "Vadnagar",
        "Manavadar",
        "Salaya",
        "Vijapur",
        "Pardi",
        "Rapar",
        "Songadh",
        "Lathi",
        "Adalaj",
        "Chhapra",
        "Gandhinagar"
      ],
      "Telangana": [
        "Hyderabad",
        "Warangal",
        "Nizamabad",
        "Karimnagar",
        "Ramagundam",
        "Khammam",
        "Mahbubnagar",
        "Mancherial",
        "Adilabad",
        "Suryapet",
        "Jagtial",
        "Miryalaguda",
        "Nirmal",
        "Kamareddy",
        "Kothagudem",
        "Bodhan",
        "Palwancha",
        "Mandamarri",
        "Koratla",
        "Sircilla",
        "Tandur",
        "Siddipet",
        "Wanaparthy",
        "Kagaznagar",
        "Gadwal",
        "Sangareddy",
        "Bellampalle",
        "Bhongir",
        "Vikarabad",
        "Jangaon",
        "Bhadrachalam",
        "Bhainsa",
        "Farooqnagar",
        "Medak",
        "Narayanpet",
        "Sadasivpet",
        "Yellandu",
        "Manuguru",
        "Kyathampalle",
        "Nagarkurnool"
      ],
      "Meghalaya": [
        "Shillong",
        "Tura",
        "Nongstoin"
      ],
      "Himachal Praddesh": [
        "Manali"
      ],
      "Arunachal Pradesh": [
        "Naharlagun",
        "Pasighat"
      ],
      "Maharashtra": [
        "Mumbai",
        "Pune",
        "Nagpur",
        "Thane",
        "Nashik",
        "Kalyan-Dombivali",
        "Vasai-Virar",
        "Solapur",
        "Mira-Bhayandar",
        "Bhiwandi",
        "Amravati",
        "Nanded-Waghala",
        "Sangli",
        "Malegaon",
        "Akola",
        "Latur",
        "Dhule",
        "Ahmednagar",
        "Ichalkaranji",
        "Parbhani",
        "Panvel",
        "Yavatmal",
        "Achalpur",
        "Osmanabad",
        "Nandurbar",
        "Satara",
        "Wardha",
        "Udgir",
        "Aurangabad",
        "Amalner",
        "Akot",
        "Pandharpur",
        "Shrirampur",
        "Parli",
        "Washim",
        "Ambejogai",
        "Manmad",
        "Ratnagiri",
        "Uran Islampur",
        "Pusad",
        "Sangamner",
        "Shirpur-Warwade",
        "Malkapur",
        "Wani",
        "Lonavla",
        "Talegaon Dabhade",
        "Anjangaon",
        "Umred",
        "Palghar",
        "Shegaon",
        "Ozar",
        "Phaltan",
        "Yevla",
        "Shahade",
        "Vita",
        "Umarkhed",
        "Warora",
        "Pachora",
        "Tumsar",
        "Manjlegaon",
        "Sillod",
        "Arvi",
        "Nandura",
        "Vaijapur",
        "Wadgaon Road",
        "Sailu",
        "Murtijapur",
        "Tasgaon",
        "Mehkar",
        "Yawal",
        "Pulgaon",
        "Nilanga",
        "Wai",
        "Umarga",
        "Paithan",
        "Rahuri",
        "Nawapur",
        "Tuljapur",
        "Morshi",
        "Purna",
        "Satana",
        "Pathri",
        "Sinnar",
        "Uchgaon",
        "Uran",
        "Pen",
        "Karjat",
        "Manwath",
        "Partur",
        "Sangole",
        "Mangrulpir",
        "Risod",
        "Shirur",
        "Savner",
        "Sasvad",
        "Pandharkaoda",
        "Talode",
        "Shrigonda",
        "Shirdi",
        "Raver",
        "Mukhed",
        "Rajura",
        "Vadgaon Kasba",
        "Tirora",
        "Mahad",
        "Lonar",
        "Sawantwadi",
        "Pathardi",
        "Pauni",
        "Ramtek",
        "Mul",
        "Soyagaon",
        "Mangalvedhe",
        "Narkhed",
        "Shendurjana",
        "Patur",
        "Mhaswad",
        "Loha",
        "Nandgaon",
        "Warud"
      ],
      "Goa": [
        "Marmagao",
        "Panaji",
        "Margao",
        "Mapusa"
      ],
      "West Bengal": [
        "Kolkata",
        "Siliguri",
        "Asansol",
        "Raghunathganj",
        "Kharagpur",
        "Naihati",
        "English Bazar",
        "Baharampur",
        "Hugli-Chinsurah",
        "Raiganj",
        "Jalpaiguri",
        "Santipur",
        "Balurghat",
        "Medinipur",
        "Habra",
        "Ranaghat",
        "Bankura",
        "Nabadwip",
        "Darjiling",
        "Purulia",
        "Arambagh",
        "Tamluk",
        "AlipurdUrban Agglomerationr",
        "Suri",
        "Jhargram",
        "Gangarampur",
        "Rampurhat",
        "Kalimpong",
        "Sainthia",
        "Taki",
        "Murshidabad",
        "Memari",
        "Paschim Punropara",
        "Tarakeswar",
        "Sonamukhi",
        "PandUrban Agglomeration",
        "Mainaguri",
        "Malda",
        "Panchla",
        "Raghunathpur",
        "Mathabhanga",
        "Monoharpur",
        "Srirampore",
        "Adra"
      ]
    }

    const allState = {  
      "states":[  
         {  
            "state":"Andhra Pradesh",
            "districts":[  
               "Anantapur",
               "Chittoor",
               "East Godavari",
               "Guntur",
               "Krishna",
               "Kurnool",
               "Nellore",
               "Prakasam",
               "Srikakulam",
               "Visakhapatnam",
               "Vizianagaram",
               "West Godavari",
               "YSR Kadapa"
            ]
         },
         {  
            "state":"Arunachal Pradesh",
            "districts":[  
               "Tawang",
               "West Kameng",
               "East Kameng",
               "Papum Pare",
               "Kurung Kumey",
               "Kra Daadi",
               "Lower Subansiri",
               "Upper Subansiri",
               "West Siang",
               "East Siang",
               "Siang",
               "Upper Siang",
               "Lower Siang",
               "Lower Dibang Valley",
               "Dibang Valley",
               "Anjaw",
               "Lohit",
               "Namsai",
               "Changlang",
               "Tirap",
               "Longding"
            ]
         },
         {  
            "state":"Assam",
            "districts":[  
               "Baksa",
               "Barpeta",
               "Biswanath",
               "Bongaigaon",
               "Cachar",
               "Charaideo",
               "Chirang",
               "Darrang",
               "Dhemaji",
               "Dhubri",
               "Dibrugarh",
               "Goalpara",
               "Golaghat",
               "Hailakandi",
               "Hojai",
               "Jorhat",
               "Kamrup Metropolitan",
               "Kamrup",
               "Karbi Anglong",
               "Karimganj",
               "Kokrajhar",
               "Lakhimpur",
               "Majuli",
               "Morigaon",
               "Nagaon",
               "Nalbari",
               "Dima Hasao",
               "Sivasagar",
               "Sonitpur",
               "South Salmara-Mankachar",
               "Tinsukia",
               "Udalguri",
               "West Karbi Anglong"
            ]
         },
         {  
            "state":"Bihar",
            "districts":[  
               "Araria",
               "Arwal",
               "Aurangabad",
               "Banka",
               "Begusarai",
               "Bhagalpur",
               "Bhojpur",
               "Buxar",
               "Darbhanga",
               "East Champaran (Motihari)",
               "Gaya",
               "Gopalganj",
               "Jamui",
               "Jehanabad",
               "Kaimur (Bhabua)",
               "Katihar",
               "Khagaria",
               "Kishanganj",
               "Lakhisarai",
               "Madhepura",
               "Madhubani",
               "Munger (Monghyr)",
               "Muzaffarpur",
               "Nalanda",
               "Nawada",
               "Patna",
               "Purnia (Purnea)",
               "Rohtas",
               "Saharsa",
               "Samastipur",
               "Saran",
               "Sheikhpura",
               "Sheohar",
               "Sitamarhi",
               "Siwan",
               "Supaul",
               "Vaishali",
               "West Champaran"
            ]
         },
         {  
            "state":"Chandigarh (UT)",
            "districts":[  
               "Chandigarh"
            ]
         },
         {  
            "state":"Chhattisgarh",
            "districts":[  
               "Balod",
               "Baloda Bazar",
               "Balrampur",
               "Bastar",
               "Bemetara",
               "Bijapur",
               "Bilaspur",
               "Dantewada (South Bastar)",
               "Dhamtari",
               "Durg",
               "Gariyaband",
               "Janjgir-Champa",
               "Jashpur",
               "Kabirdham (Kawardha)",
               "Kanker (North Bastar)",
               "Kondagaon",
               "Korba",
               "Korea (Koriya)",
               "Mahasamund",
               "Mungeli",
               "Narayanpur",
               "Raigarh",
               "Raipur",
               "Rajnandgaon",
               "Sukma",
               "Surajpur  ",
               "Surguja"
            ]
         },
         {  
            "state":"Dadra and Nagar Haveli (UT)",
            "districts":[  
               "Dadra & Nagar Haveli"
            ]
         },
         {  
            "state":"Daman and Diu (UT)",
            "districts":[  
               "Daman",
               "Diu"
            ]
         },
         {  
            "state":"Delhi (NCT)",
            "districts":[  
               "Central Delhi",
               "East Delhi",
               "New Delhi",
               "North Delhi",
               "North East  Delhi",
               "North West  Delhi",
               "Shahdara",
               "South Delhi",
               "South East Delhi",
               "South West  Delhi",
               "West Delhi"
            ]
         },
         {  
            "state":"Goa",
            "districts":[  
               "North Goa",
               "South Goa"
            ]
         },
         {  
            "state":"Gujarat",
            "districts":[  
               "Ahmedabad",
               "Amreli",
               "Anand",
               "Aravalli",
               "Banaskantha (Palanpur)",
               "Bharuch",
               "Bhavnagar",
               "Botad",
               "Chhota Udepur",
               "Dahod",
               "Dangs (Ahwa)",
               "Devbhoomi Dwarka",
               "Gandhinagar",
               "Gir Somnath",
               "Jamnagar",
               "Junagadh",
               "Kachchh",
               "Kheda (Nadiad)",
               "Mahisagar",
               "Mehsana",
               "Morbi",
               "Narmada (Rajpipla)",
               "Navsari",
               "Panchmahal (Godhra)",
               "Patan",
               "Porbandar",
               "Rajkot",
               "Sabarkantha (Himmatnagar)",
               "Surat",
               "Surendranagar",
               "Tapi (Vyara)",
               "Vadodara",
               "Valsad"
            ]
         },
         {  
            "state":"Haryana",
            "districts":[  
               "Ambala",
               "Bhiwani",
               "Charkhi Dadri",
               "Faridabad",
               "Fatehabad",
               "Gurgaon",
               "Hisar",
               "Jhajjar",
               "Jind",
               "Kaithal",
               "Karnal",
               "Kurukshetra",
               "Mahendragarh",
               "Mewat",
               "Palwal",
               "Panchkula",
               "Panipat",
               "Rewari",
               "Rohtak",
               "Sirsa",
               "Sonipat",
               "Yamunanagar"
            ]
         },
         {  
            "state":"Himachal Pradesh",
            "districts":[  
               "Bilaspur",
               "Chamba",
               "Hamirpur",
               "Kangra",
               "Kinnaur",
               "Kullu",
               "Lahaul &amp; Spiti",
               "Mandi",
               "Shimla",
               "Sirmaur (Sirmour)",
               "Solan",
               "Una"
            ]
         },
         {  
            "state":"Jammu and Kashmir",
            "districts":[  
               "Anantnag",
               "Bandipore",
               "Baramulla",
               "Budgam",
               "Doda",
               "Ganderbal",
               "Jammu",
               "Kargil",
               "Kathua",
               "Kishtwar",
               "Kulgam",
               "Kupwara",
               "Leh",
               "Poonch",
               "Pulwama",
               "Rajouri",
               "Ramban",
               "Reasi",
               "Samba",
               "Shopian",
               "Srinagar",
               "Udhampur"
            ]
         },
         {  
            "state":"Jharkhand",
            "districts":[  
               "Bokaro",
               "Chatra",
               "Deoghar",
               "Dhanbad",
               "Dumka",
               "East Singhbhum",
               "Garhwa",
               "Giridih",
               "Godda",
               "Gumla",
               "Hazaribag",
               "Jamtara",
               "Khunti",
               "Koderma",
               "Latehar",
               "Lohardaga",
               "Pakur",
               "Palamu",
               "Ramgarh",
               "Ranchi",
               "Sahibganj",
               "Seraikela-Kharsawan",
               "Simdega",
               "West Singhbhum"
            ]
         },
         {  
            "state":"Karnataka",
            "districts":[  
               "Bagalkot",
               "Ballari (Bellary)",
               "Belagavi (Belgaum)",
               "Bengaluru (Bangalore) Rural",
               "Bengaluru (Bangalore) Urban",
               "Bidar",
               "Chamarajanagar",
               "Chikballapur",
               "Chikkamagaluru (Chikmagalur)",
               "Chitradurga",
               "Dakshina Kannada",
               "Davangere",
               "Dharwad",
               "Gadag",
               "Hassan",
               "Haveri",
               "Kalaburagi (Gulbarga)",
               "Kodagu",
               "Kolar",
               "Koppal",
               "Mandya",
               "Mysuru (Mysore)",
               "Raichur",
               "Ramanagara",
               "Shivamogga (Shimoga)",
               "Tumakuru (Tumkur)",
               "Udupi",
               "Uttara Kannada (Karwar)",
               "Vijayapura (Bijapur)",
               "Yadgir"
            ]
         },
         {  
            "state":"Kerala",
            "districts":[  
               "Alappuzha",
               "Ernakulam",
               "Idukki",
               "Kannur",
               "Kasaragod",
               "Kollam",
               "Kottayam",
               "Kozhikode",
               "Malappuram",
               "Palakkad",
               "Pathanamthitta",
               "Thiruvananthapuram",
               "Thrissur",
               "Wayanad"
            ]
         },
         {  
            "state":"Lakshadweep (UT)",
            "districts":[  
               "Agatti",
               "Amini",
               "Androth",
               "Bithra",
               "Chethlath",
               "Kavaratti",
               "Kadmath",
               "Kalpeni",
               "Kilthan",
               "Minicoy"
            ]
         },
         {  
            "state":"Madhya Pradesh",
            "districts":[  
               "Agar Malwa",
               "Alirajpur",
               "Anuppur",
               "Ashoknagar",
               "Balaghat",
               "Barwani",
               "Betul",
               "Bhind",
               "Bhopal",
               "Burhanpur",
               "Chhatarpur",
               "Chhindwara",
               "Damoh",
               "Datia",
               "Dewas",
               "Dhar",
               "Dindori",
               "Guna",
               "Gwalior",
               "Harda",
               "Hoshangabad",
               "Indore",
               "Jabalpur",
               "Jhabua",
               "Katni",
               "Khandwa",
               "Khargone",
               "Mandla",
               "Mandsaur",
               "Morena",
               "Narsinghpur",
               "Neemuch",
               "Panna",
               "Raisen",
               "Rajgarh",
               "Ratlam",
               "Rewa",
               "Sagar",
               "Satna",
               "Sehore",
               "Seoni",
               "Shahdol",
               "Shajapur",
               "Sheopur",
               "Shivpuri",
               "Sidhi",
               "Singrauli",
               "Tikamgarh",
               "Ujjain",
               "Umaria",
               "Vidisha"
            ]
         },
         {  
            "state":"Maharashtra",
            "districts":[  
               "Ahmednagar",
               "Akola",
               "Amravati",
               "Aurangabad",
               "Beed",
               "Bhandara",
               "Buldhana",
               "Chandrapur",
               "Dhule",
               "Gadchiroli",
               "Gondia",
               "Hingoli",
               "Jalgaon",
               "Jalna",
               "Kolhapur",
               "Latur",
               "Mumbai City",
               "Mumbai Suburban",
               "Nagpur",
               "Nanded",
               "Nandurbar",
               "Nashik",
               "Osmanabad",
               "Palghar",
               "Parbhani",
               "Pune",
               "Raigad",
               "Ratnagiri",
               "Sangli",
               "Satara",
               "Sindhudurg",
               "Solapur",
               "Thane",
               "Wardha",
               "Washim",
               "Yavatmal"
            ]
         },
         {  
            "state":"Manipur",
            "districts":[  
               "Bishnupur",
               "Chandel",
               "Churachandpur",
               "Imphal East",
               "Imphal West",
               "Jiribam",
               "Kakching",
               "Kamjong",
               "Kangpokpi",
               "Noney",
               "Pherzawl",
               "Senapati",
               "Tamenglong",
               "Tengnoupal",
               "Thoubal",
               "Ukhrul"
            ]
         },
         {  
            "state":"Meghalaya",
            "districts":[  
               "East Garo Hills",
               "East Jaintia Hills",
               "East Khasi Hills",
               "North Garo Hills",
               "Ri Bhoi",
               "South Garo Hills",
               "South West Garo Hills ",
               "South West Khasi Hills",
               "West Garo Hills",
               "West Jaintia Hills",
               "West Khasi Hills"
            ]
         },
         {  
            "state":"Mizoram",
            "districts":[  
               "Aizawl",
               "Champhai",
               "Kolasib",
               "Lawngtlai",
               "Lunglei",
               "Mamit",
               "Saiha",
               "Serchhip"
            ]
         },
         {  
            "state":"Nagaland",
            "districts":[  
               "Dimapur",
               "Kiphire",
               "Kohima",
               "Longleng",
               "Mokokchung",
               "Mon",
               "Peren",
               "Phek",
               "Tuensang",
               "Wokha",
               "Zunheboto"
            ]
         },
         {  
            "state":"Odisha",
            "districts":[  
               "Angul",
               "Balangir",
               "Balasore",
               "Bargarh",
               "Bhadrak",
               "Boudh",
               "Cuttack",
               "Deogarh",
               "Dhenkanal",
               "Gajapati",
               "Ganjam",
               "Jagatsinghapur",
               "Jajpur",
               "Jharsuguda",
               "Kalahandi",
               "Kandhamal",
               "Kendrapara",
               "Kendujhar (Keonjhar)",
               "Khordha",
               "Koraput",
               "Malkangiri",
               "Mayurbhanj",
               "Nabarangpur",
               "Nayagarh",
               "Nuapada",
               "Puri",
               "Rayagada",
               "Sambalpur",
               "Sonepur",
               "Sundargarh"
            ]
         },
         {  
            "state":"Puducherry (UT)",
            "districts":[  
               "Karaikal",
               "Mahe",
               "Pondicherry",
               "Yanam"
            ]
         },
         {  
            "state":"Punjab",
            "districts":[  
               "Amritsar",
               "Barnala",
               "Bathinda",
               "Faridkot",
               "Fatehgarh Sahib",
               "Fazilka",
               "Ferozepur",
               "Gurdaspur",
               "Hoshiarpur",
               "Jalandhar",
               "Kapurthala",
               "Ludhiana",
               "Mansa",
               "Moga",
               "Muktsar",
               "Nawanshahr (Shahid Bhagat Singh Nagar)",
               "Pathankot",
               "Patiala",
               "Rupnagar",
               "Sahibzada Ajit Singh Nagar (Mohali)",
               "Sangrur",
               "Tarn Taran"
            ]
         },
         {  
            "state":"Rajasthan",
            "districts":[  
               "Ajmer",
               "Alwar",
               "Banswara",
               "Baran",
               "Barmer",
               "Bharatpur",
               "Bhilwara",
               "Bikaner",
               "Bundi",
               "Chittorgarh",
               "Churu",
               "Dausa",
               "Dholpur",
               "Dungarpur",
               "Hanumangarh",
               "Jaipur",
               "Jaisalmer",
               "Jalore",
               "Jhalawar",
               "Jhunjhunu",
               "Jodhpur",
               "Karauli",
               "Kota",
               "Nagaur",
               "Pali",
               "Pratapgarh",
               "Rajsamand",
               "Sawai Madhopur",
               "Sikar",
               "Sirohi",
               "Sri Ganganagar",
               "Tonk",
               "Udaipur"
            ]
         },
         {  
            "state":"Sikkim",
            "districts":[  
               "East Sikkim",
               "North Sikkim",
               "South Sikkim",
               "West Sikkim"
            ]
         },
         {  
            "state":"Tamil Nadu",
            "districts":[  
               "Ariyalur",
               "Chennai",
               "Coimbatore",
               "Cuddalore",
               "Dharmapuri",
               "Dindigul",
               "Erode",
               "Kanchipuram",
               "Kanyakumari",
               "Karur",
               "Krishnagiri",
               "Madurai",
               "Nagapattinam",
               "Namakkal",
               "Nilgiris",
               "Perambalur",
               "Pudukkottai",
               "Ramanathapuram",
               "Salem",
               "Sivaganga",
               "Thanjavur",
               "Theni",
               "Thoothukudi (Tuticorin)",
               "Tiruchirappalli",
               "Tirunelveli",
               "Tiruppur",
               "Tiruvallur",
               "Tiruvannamalai",
               "Tiruvarur",
               "Vellore",
               "Viluppuram",
               "Virudhunagar"
            ]
         },
         {  
            "state":"Telangana",
            "districts":[  
               "Adilabad",
               "Bhadradri Kothagudem",
               "Hyderabad",
               "Jagtial",
               "Jangaon",
               "Jayashankar Bhoopalpally",
               "Jogulamba Gadwal",
               "Kamareddy",
               "Karimnagar",
               "Khammam",
               "Komaram Bheem Asifabad",
               "Mahabubabad",
               "Mahabubnagar",
               "Mancherial",
               "Medak",
               "Medchal",
               "Nagarkurnool",
               "Nalgonda",
               "Nirmal",
               "Nizamabad",
               "Peddapalli",
               "Rajanna Sircilla",
               "Rangareddy",
               "Sangareddy",
               "Siddipet",
               "Suryapet",
               "Vikarabad",
               "Wanaparthy",
               "Warangal (Rural)",
               "Warangal (Urban)",
               "Yadadri Bhuvanagiri"
            ]
         },
         {  
            "state":"Tripura",
            "districts":[  
               "Dhalai",
               "Gomati",
               "Khowai",
               "North Tripura",
               "Sepahijala",
               "South Tripura",
               "Unakoti",
               "West Tripura"
            ]
         },
         {  
            "state":"Uttarakhand",
            "districts":[  
               "Almora",
               "Bageshwar",
               "Chamoli",
               "Champawat",
               "Dehradun",
               "Haridwar",
               "Nainital",
               "Pauri Garhwal",
               "Pithoragarh",
               "Rudraprayag",
               "Tehri Garhwal",
               "Udham Singh Nagar",
               "Uttarkashi"
            ]
         },
         {  
            "state":"Uttar Pradesh",
            "districts":[  
               "Agra",
               "Aligarh",
               "Allahabad",
               "Ambedkar Nagar",
               "Amethi (Chatrapati Sahuji Mahraj Nagar)",
               "Amroha (J.P. Nagar)",
               "Auraiya",
               "Azamgarh",
               "Baghpat",
               "Bahraich",
               "Ballia",
               "Balrampur",
               "Banda",
               "Barabanki",
               "Bareilly",
               "Basti",
               "Bhadohi",
               "Bijnor",
               "Budaun",
               "Bulandshahr",
               "Chandauli",
               "Chitrakoot",
               "Deoria",
               "Etah",
               "Etawah",
               "Faizabad",
               "Farrukhabad",
               "Fatehpur",
               "Firozabad",
               "Gautam Buddha Nagar",
               "Ghaziabad",
               "Ghazipur",
               "Gonda",
               "Gorakhpur",
               "Hamirpur",
               "Hapur (Panchsheel Nagar)",
               "Hardoi",
               "Hathras",
               "Jalaun",
               "Jaunpur",
               "Jhansi",
               "Kannauj",
               "Kanpur Dehat",
               "Kanpur Nagar",
               "Kanshiram Nagar (Kasganj)",
               "Kaushambi",
               "Kushinagar (Padrauna)",
               "Lakhimpur - Kheri",
               "Lalitpur",
               "Lucknow",
               "Maharajganj",
               "Mahoba",
               "Mainpuri",
               "Mathura",
               "Mau",
               "Meerut",
               "Mirzapur",
               "Moradabad",
               "Muzaffarnagar",
               "Pilibhit",
               "Pratapgarh",
               "RaeBareli",
               "Rampur",
               "Saharanpur",
               "Sambhal (Bhim Nagar)",
               "Sant Kabir Nagar",
               "Shahjahanpur",
               "Shamali (Prabuddh Nagar)",
               "Shravasti",
               "Siddharth Nagar",
               "Sitapur",
               "Sonbhadra",
               "Sultanpur",
               "Unnao",
               "Varanasi"
            ]
         },
         {  
            "state":"West Bengal",
            "districts":[  
               "Alipurduar",
               "Bankura",
               "Birbhum",
               "Burdwan (Bardhaman)",
               "Cooch Behar",
               "Dakshin Dinajpur (South Dinajpur)",
               "Darjeeling",
               "Hooghly",
               "Howrah",
               "Jalpaiguri",
               "Kalimpong",
               "Kolkata",
               "Malda",
               "Murshidabad",
               "Nadia",
               "North 24 Parganas",
               "Paschim Medinipur (West Medinipur)",
               "Purba Medinipur (East Medinipur)",
               "Purulia",
               "South 24 Parganas",
               "Uttar Dinajpur (North Dinajpur)"
            ]
         }
      ]
   }
   export default allState;